# Generated by Django 4.2.4 on 2025-12-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('order_data', models.DateField(auto_now_add=True)),
                ('is_shipped', models.BooleanField(default=False)),
            ],
        ),
    ]
