# Generated by Django 4.2.4 on 2025-12-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('related_objects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructors',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='learner',
            new_name='learners',
        ),
    ]
